-- PR1 foundation migration:
-- - student profile backend
-- - outsider recruitment inquiry backend
-- - future-ready role model with tpo_admin

create extension if not exists pgcrypto;

do $$
begin
  if not exists (
    select 1 from pg_type where typname = 'app_role'
  ) then
    create type public.app_role as enum ('student', 'tpo_admin');
  end if;
end
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.app_role not null default 'student',
  full_name text not null check (char_length(trim(full_name)) > 1),
  college_email text not null unique,
  roll_number text not null,
  branch text not null,
  batch text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create table if not exists public.recruitment_inquiries (
  id bigint generated by default as identity primary key,
  company_name text not null check (char_length(trim(company_name)) > 1),
  website text,
  industry text not null,
  company_size text,
  contact_name text not null,
  designation text not null,
  email text not null,
  phone text not null,
  role text not null,
  positions integer not null check (positions > 0),
  preferred_branches text[] not null default '{}',
  additional_info text,
  consent boolean not null default true,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_recruitment_inquiries_updated_at
before update on public.recruitment_inquiries
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.recruitment_inquiries enable row level security;

create policy "profiles_select_self_or_admin"
on public.profiles
for select
to authenticated
using (
  auth.uid() = id
  or coalesce(auth.jwt() ->> 'role', '') = 'tpo_admin'
);

create policy "profiles_insert_self"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "profiles_update_self_or_admin"
on public.profiles
for update
to authenticated
using (
  auth.uid() = id
  or coalesce(auth.jwt() ->> 'role', '') = 'tpo_admin'
)
with check (
  auth.uid() = id
  or coalesce(auth.jwt() ->> 'role', '') = 'tpo_admin'
);

create policy "recruitment_inquiries_insert_public"
on public.recruitment_inquiries
for insert
to anon, authenticated
with check (true);

create policy "recruitment_inquiries_admin_read"
on public.recruitment_inquiries
for select
to authenticated
using (coalesce(auth.jwt() ->> 'role', '') = 'tpo_admin');

create policy "recruitment_inquiries_admin_update"
on public.recruitment_inquiries
for update
to authenticated
using (coalesce(auth.jwt() ->> 'role', '') = 'tpo_admin')
with check (coalesce(auth.jwt() ->> 'role', '') = 'tpo_admin');

create policy "recruitment_inquiries_admin_delete"
on public.recruitment_inquiries
for delete
to authenticated
using (coalesce(auth.jwt() ->> 'role', '') = 'tpo_admin');

create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_profiles_college_email on public.profiles(college_email);
create index if not exists idx_inquiries_created_at on public.recruitment_inquiries(created_at desc);
create index if not exists idx_inquiries_email on public.recruitment_inquiries(email);
create index if not exists idx_inquiries_status on public.recruitment_inquiries(status);
